[package]
name = "openidconnect"
version = "2.3.2"
authors = ["David A. Ramos <ramos@cs.stanford.edu>"]
description = "OpenID Connect library"
license = "MIT"
repository = "https://github.com/ramosbugs/openidconnect-rs"
edition = "2018"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["reqwest", "rustls-tls"]
curl = ["oauth2/curl"]
reqwest = ["oauth2/reqwest"]
ureq = ["oauth2/ureq"]
native-tls = ["oauth2/native-tls"]
rustls-tls = ["oauth2/rustls-tls"]
accept-rfc3339-timestamps = []
nightly = []

[dependencies]
base64 = "0.13"
thiserror = "1.0"
http = "0.2"
itertools = "0.10"
log = "0.4"
oauth2 = { version = "4.2", default-features = false }
rand = "0.8"
ring = "0.16"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_path_to_error = "0.1"
serde-value = "0.7"
time = { version = "0.3", features = ["parsing", "std"] }
url = { version = "2.1", features = ["serde"] }
num-bigint = "0.4.3"

[dev-dependencies]
color-backtrace = { version = "0.5" }
env_logger = "0.9"
pretty_assertions = "1.0"
reqwest_ = { package = "reqwest", features = [
    "blocking",
    "rustls-tls",
], version = "0.11", default-features = false }
retry = "1.0"
anyhow = "1.0"
